# Generated by Django 4.0.8 on 2022-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_owner_email_student_email_teacher_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
    ]
