# Generated by Django 4.0.8 on 2022-11-08 10:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_rename_phonenumber_owner_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experties",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="classgrade",
            name="teacher",
        ),
        migrations.CreateModel(
            name="TeacherClasses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.teacher"
                    ),
                ),
            ],
        ),
    ]
