# Generated by Django 4.0.8 on 2022-11-09 05:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_experties_remove_classgrade_teacher_teacherclasses"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherClasse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_grade", models.UUIDField(default=uuid.uuid4)),
                ("teacher", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AddField(
            model_name="experties",
            name="teacher",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="student",
            name="class_grade",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name="TeacherClasses",
        ),
    ]
