# Generated by Django 4.0.8 on 2022-11-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_teacherclasse_experties_teacher_student_class_grade_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeacherClasse",
            new_name="TeacherClass",
        ),
        migrations.RenameModel(
            old_name="Experties",
            new_name="TeacherExperties",
        ),
    ]
